inherit_from: .rubocop_todo.yml

# frozen_string_literal: true

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'website/**/*'
    - 'spec/support/opal/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Metrics
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 10

# Naming
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

# RSpec
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
