= Plurimath Parslet

This is a fork of the original Parslet gem, which is a parser library for Ruby.

This differs from the original Parslet gem, such that it is Opal (JS based Ruby)
compatible.


== Introduction

Parslet makes developing complex parsers easy. It does so by:

* providing the best error reporting possible
* not generating reams of code for you to debug

Parslet takes the long way around to make your job easier. It allows for
incremental language construction. Often, you start out small, implementing
the atoms of your language first; _parslet_ takes pride in making this
possible.

Eager to try this out? Please see the associated web site:
https://kschiess.github.io/parslet/

== Synopsis

[source,ruby]
----
require 'parslet'
include Parslet

# parslet parses strings
str('foo').
  parse('foo') # => "foo"@0

# it matches character sets
match['abc'].parse('a') # => "a"@0
match['abc'].parse('b') # => "b"@0
match['abc'].parse('c') # => "c"@0

# and it annotates its output
str('foo').as(:important_bit).
  parse('foo') # => {:important_bit=>"foo"@0}

# you can construct parsers with just a few lines
quote = str('"')
simple_string = quote >> (quote.absent? >> any).repeat >> quote

simple_string.
  parse('"Simple Simple Simple"') # => "\"Simple Simple Simple\""@0

# or by making a fuss about it
class Smalltalk < Parslet::Parser
  root :smalltalk

  rule(:smalltalk) { statements }
  rule(:statements) {
    # insert smalltalk parser here (outside of the scope of this readme)
  }
end

# and then
Smalltalk.new.parse('smalltalk')
----

== Features

* Tools for every part of the parser chain
* Transformers generate Abstract Syntax Trees
* Accelerators transform parsers, making them quite a bit faster
* Pluggable error reporters
* Graphviz export for your parser
* Rspec testing support rig
* Simply Ruby, composable and hackable

== Compatibility

This library is intended to work with Ruby variants >= 2.7. It has been tested on:

* MRI Ruby 2.7+
* JRuby
* Opal (JavaScript-based Ruby)

Please report as a bug if you encounter issues.

== Status

Production worthy.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'plurimath-parslet'
----

And then execute:

[source,bash]
----
$ bundle install
----

Or install it yourself as:

[source,bash]
----
$ gem install plurimath-parslet
----

== Usage

[source,ruby]
----
require 'parslet'
----

The gem maintains the original `parslet` namespace for compatibility.

== Development

After checking out the repo, run:

[source,bash]
----
$ bundle install
----

To run the tests:

[source,bash]
----
$ bundle exec rake spec
----

To run Opal (JavaScript) tests:

[source,bash]
----
$ bundle exec rake spec:opal
----

== Contributing

. Fork it
. Create your feature branch (`git checkout -b my-new-feature`)
. Commit your changes (`git commit -am 'Add some feature'`)
. Push to the branch (`git push origin my-new-feature`)
. Create a new Pull Request

== License

The gem is available as open source under the terms of the MIT License.

== Copyright

(c) 2010-2018 Kaspar Schiess.

2025 Augmented by Ribose Inc.
